package vn.edu.school.schedule.notification;

import io.micrometer.core.instrument.MeterRegistry;
import java.util.List;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

@Component
public class OutboxWorker {
    private final JdbcTemplate jdbc; private final TransactionTemplate tx; private final ObjectMapper json;
    private final EmailSender email; private final MeterRegistry metrics; private final int maxAttempts;
    public OutboxWorker(JdbcTemplate jdbc,TransactionTemplate tx,ObjectMapper json,EmailSender email,MeterRegistry metrics,
                        @Value("${app.email.max-attempts:3}")int maxAttempts){this.jdbc=jdbc;this.tx=tx;this.json=json;this.email=email;this.metrics=metrics;this.maxAttempts=maxAttempts;}
    @Scheduled(fixedDelayString="${app.outbox.poll-delay-ms:5000}",initialDelayString="${app.outbox.initial-delay-ms:5000}") public void poll(){jdbc.update("UPDATE outbox_messages SET status='PENDING',locked_until=NULL WHERE status='PROCESSING' AND locked_until<now()");drain();}
    public int drain(){int count=0;for(int i=0;i<100;i++){Claim claim=claim();if(claim==null)break;process(claim);count++;}return count;}
    private Claim claim(){return tx.execute(status->{List<Claim> rows=jdbc.query("SELECT id,event_type,aggregate_id,deduplication_key,payload::text,attempt_count FROM outbox_messages WHERE status='PENDING' AND available_at<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1",(rs,row)->new Claim(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,UUID.class),rs.getString(4),rs.getString(5),rs.getInt(6)));if(rows.isEmpty())return null;Claim c=rows.getFirst();jdbc.update("UPDATE outbox_messages SET status='PROCESSING',locked_until=now()+interval '2 minutes' WHERE id=?",c.id());return c;});}
    private void process(Claim claim){try{JsonNode payload=json.readTree(claim.payload());boolean website=payload.path("notifyWebsite").isMissingNode()||payload.path("notifyWebsite").asBoolean(true);boolean sendEmail=payload.path("notifyEmail").asBoolean(false);Message message=message(claim);List<Recipient> recipients=recipients(claim,payload);if(website)createNotification(claim,message,recipients);if(sendEmail)for(Recipient recipient:recipients)email.send(recipient.email(),message.title(),message.body());jdbc.update("UPDATE outbox_messages SET status='PROCESSED',processed_at=now(),locked_until=NULL,attempt_count=attempt_count+1 WHERE id=?",claim.id());metrics.counter("schedule.outbox.processed","type",claim.type()).increment();}catch(Exception exception){int next=claim.attempts()+1;String state=next>=maxAttempts?"FAILED":"PENDING";jdbc.update("UPDATE outbox_messages SET status=?,attempt_count=?,available_at=now()+interval '1 minute',locked_until=NULL WHERE id=?",state,next,claim.id());metrics.counter("schedule.outbox.failed","type",claim.type()).increment();}}
    private Message message(Claim claim){return switch(claim.type()){case "WEEKLY_PLAN_PUBLISHED"->new Message("Kế hoạch tuần đã được công bố","Kế hoạch tuần mới đã sẵn sàng.","WeeklyPlan");case "WEEKLY_PLAN_UPDATED"->new Message("Kế hoạch tuần đã cập nhật","Nội dung kế hoạch tuần vừa thay đổi.","WeeklyPlan");case "TASK_ASSIGNED"->new Message("Bạn có nhiệm vụ mới",taskTitle(claim.aggregateId()),"Task");case "TASK_UPDATED"->new Message("Nhiệm vụ đã cập nhật",taskTitle(claim.aggregateId()),"Task");case "SATURDAY_PLAN_REMINDER"->new Message("Kế hoạch tuần tới chưa công bố","Vui lòng kiểm tra và công bố kế hoạch tuần tới.","SchoolWeek");case "CONVERSATION_OPENED","CONVERSATION_MESSAGE"->new Message("Có trao đổi mới","Một cuộc trao đổi vừa có nội dung mới.","Conversation");case "CONVERSATION_CLOSED"->new Message("Trao đổi đã đóng","Cuộc trao đổi của bạn đã được đóng.","Conversation");default->new Message("Thông báo hệ thống",claim.type(),"System");};}
    private String taskTitle(UUID id){List<String> rows=jdbc.query("SELECT title FROM tasks WHERE id=?",(rs,row)->rs.getString(1),id);return rows.isEmpty()?"Nhiệm vụ":rows.getFirst();}
    private List<Recipient> recipients(Claim claim,JsonNode payload){if(claim.type().startsWith("TASK_")){UUID id=UUID.fromString(payload.path("assigneeUserId").asText());return jdbc.query("SELECT id,email FROM users WHERE id=? AND status='ACTIVE'",(rs,row)->new Recipient(rs.getObject(1,UUID.class),rs.getString(2)),id);}if("SATURDAY_PLAN_REMINDER".equals(claim.type())){UUID id=UUID.fromString(payload.path("adminUserId").asText());return jdbc.query("SELECT id,email FROM users WHERE id=? AND status='ACTIVE'",(rs,row)->new Recipient(rs.getObject(1,UUID.class),rs.getString(2)),id);}if(claim.type().startsWith("CONVERSATION_")){UUID id=UUID.fromString(payload.path("recipientUserId").asText());return jdbc.query("SELECT id,email FROM users WHERE id=? AND status='ACTIVE'",(rs,row)->new Recipient(rs.getObject(1,UUID.class),rs.getString(2)),id);}return jdbc.query("SELECT id,email FROM users WHERE status='ACTIVE' AND system_role='USER' ORDER BY id",(rs,row)->new Recipient(rs.getObject(1,UUID.class),rs.getString(2)));}
    private void createNotification(Claim claim,Message message,List<Recipient> recipients){UUID id=UUID.nameUUIDFromBytes(("notification:"+claim.key()).getBytes(java.nio.charset.StandardCharsets.UTF_8));jdbc.update("INSERT INTO notifications(id,type,title,body,entity_type,entity_id,deduplication_key) VALUES (?,?,?,?,?,?,?) ON CONFLICT(deduplication_key) DO NOTHING",id,claim.type(),message.title(),message.body(),message.entityType(),claim.aggregateId(),claim.key());for(Recipient recipient:recipients)jdbc.update("INSERT INTO notification_recipients(notification_id,user_id,sent_at) VALUES (?,?,now()) ON CONFLICT DO NOTHING",id,recipient.id());}
    private record Claim(UUID id,String type,UUID aggregateId,String key,String payload,int attempts){} private record Recipient(UUID id,String email){} private record Message(String title,String body,String entityType){}
}
