"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import type { EventItem } from "@/types/domain";
import { Dialog } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

const eventSchema = z.object({ content: z.string().trim().min(1, "Vui lòng nhập nội dung"), startDate: z.string().optional(), endDate: z.string().optional(), session: z.enum(["MORNING", "AFTERNOON"]).optional().or(z.literal("")), startTime: z.string().optional(), endTime: z.string().optional(), location: z.string().optional(), note: z.string().optional() }).refine((value) => !value.startDate || !value.endDate || value.startDate <= value.endDate, { message: "Ngày kết thúc phải từ ngày bắt đầu", path: ["endDate"] });
type EventForm = z.infer<typeof eventSchema>;
export function EventFormDialog({ open, onOpenChange, defaultDate, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; defaultDate?: string; onSubmit: (value: Omit<EventItem, "id">) => void }) { const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<EventForm>({ resolver: zodResolver(eventSchema), defaultValues: { content: "", startDate: defaultDate, endDate: "", session: "", startTime: "", endTime: "", location: "", note: "" } }); return <Dialog open={open} onOpenChange={(next) => { onOpenChange(next); if (!next) reset(); }} title="Thêm sự kiện" description="Chỉ nội dung là bắt buộc. Có thể tạo sự kiện kéo dài nhiều ngày."><form className="space-y-4" onSubmit={handleSubmit(async (data) => { onSubmit({ ...data, session: data.session || undefined }); onOpenChange(false); reset(); })}><label><span className="field-label">Nội dung *</span><textarea className="field min-h-24" placeholder="Ví dụ: Họp hội đồng sư phạm" {...register("content")}/>{errors.content && <span className="text-xs text-red-600">{errors.content.message}</span>}</label><div className="grid gap-4 sm:grid-cols-2"><Field label="Ngày bắt đầu"><input className="field" type="date" {...register("startDate")}/></Field><Field label="Ngày kết thúc"><input className="field" type="date" {...register("endDate")}/>{errors.endDate && <span className="text-xs text-red-600">{errors.endDate.message}</span>}</Field><Field label="Buổi"><select className="field" {...register("session")}><option value="">Không xác định</option><option value="MORNING">Buổi sáng</option><option value="AFTERNOON">Buổi chiều</option></select></Field><span/><Field label="Giờ bắt đầu"><input className="field" type="time" {...register("startTime")}/></Field><Field label="Giờ kết thúc"><input className="field" type="time" {...register("endTime")}/></Field></div><Field label="Địa điểm"><input className="field" {...register("location")}/></Field><Field label="Ghi chú"><textarea className="field min-h-20" {...register("note")}/></Field><div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="secondary" onClick={() => onOpenChange(false)}>Hủy</Button><Button disabled={isSubmitting} type="submit">Thêm sự kiện</Button></div></form></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="field-label">{label}</span>{children}</label>; }
