"use client";

import { AlertTriangle, CheckCircle2, XCircle } from "lucide-react";
import { Dialog } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { PlanValidation } from "@/services";

export function PublishReviewDialog({ open, onOpenChange, review, busy, onPublish }: { open: boolean; onOpenChange: (value: boolean) => void; review?: PlanValidation; busy?: boolean; onPublish: () => void }) { const blocking = Boolean(review?.errors.length); return <Dialog open={open} onOpenChange={onOpenChange} title="Kiểm tra trước khi công bố" description="Kết quả được tính trực tiếp từ dữ liệu đã lưu trên máy chủ."><div className="space-y-3">{!blocking && <Check text="Kế hoạch có cấu trúc hợp lệ"/>}{review?.warnings.map((item, index) => <Warning key={`${item.code}-${index}`} text={item.message}/>)}{review?.errors.map((item, index) => <ErrorItem key={`${item.code}-${index}`} text={item.message}/>)}</div><div className="dialog-actions"><Button variant="secondary" onClick={() => onOpenChange(false)}>Quay lại</Button><Button disabled={blocking || busy} onClick={onPublish}>{blocking ? "Không thể công bố" : busy ? "Đang công bố…" : review?.warnings.length ? "Công bố dù còn cảnh báo" : "Công bố"}</Button></div></Dialog>; }
function Check({ text }: { text: string }) { return <p className="flex gap-3 rounded-lg bg-emerald-50 p-3 text-sm font-medium text-emerald-800"><CheckCircle2 size={18}/>{text}</p>; } function Warning({ text }: { text: string }) { return <p className="flex gap-3 rounded-lg bg-amber-50 p-3 text-sm font-medium text-amber-800"><AlertTriangle size={18}/>{text}</p>; } function ErrorItem({ text }: { text: string }) { return <p className="flex gap-3 rounded-lg bg-red-50 p-3 text-sm font-medium text-red-700"><XCircle size={18}/>{text}</p>; }
