"use client";
import { Eye } from "lucide-react";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { auditService } from "@/services";
import type { AuditEntry } from "@/types/domain";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { LoadingSkeleton, ErrorState } from "@/components/ui/states";
import { formatDateTime } from "@/lib/utils";
export default function AuditPage() { const [selected, setSelected] = useState<AuditEntry>(); const query = useQuery({ queryKey: ["audit"], queryFn: () => auditService.list() }); if (query.isLoading) return <LoadingSkeleton/>; if (query.isError) return <ErrorState retry={() => query.refetch()}/>; return <><PageHeader eyebrow="Chỉ dành cho Admin" title="Audit Log" description="Nhật ký chỉ đọc giúp truy vết thay đổi. MVP không hỗ trợ rollback."/><div className="mb-5 grid gap-3 sm:grid-cols-3"><input className="field" type="date" aria-label="Từ ngày"/><select className="field" aria-label="Loại đối tượng"><option>Tất cả đối tượng</option><option>WeeklyPlan</option><option>Task</option><option>User</option></select><input className="field" placeholder="Tìm người thực hiện…" aria-label="Tìm người thực hiện"/></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Loại</th><th>Hành động</th><th>Đối tượng</th><th></th></tr></thead><tbody>{query.data?.map((item) => <tr key={item.id}><td>{formatDateTime(item.createdAt)}</td><td>{item.actor}</td><td>{item.entityType}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{item.action}</span></td><td>{item.entityLabel}</td><td><Button aria-label={`Xem thay đổi ${item.entityLabel}`} variant="ghost" size="sm" onClick={() => setSelected(item)}><Eye size={16}/></Button></td></tr>)}</tbody></table></div><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(undefined)} title="Chi tiết thay đổi" description={selected ? `${selected.actor} · ${formatDateTime(selected.createdAt)}` : undefined}><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border bg-red-50/40 p-4"><p className="eyebrow">Giá trị cũ</p><pre className="mt-3 whitespace-pre-wrap text-sm font-sans text-slate-700">{selected?.oldValue ?? "Không có"}</pre></div><div className="rounded-xl border bg-emerald-50/40 p-4"><p className="eyebrow">Giá trị mới</p><pre className="mt-3 whitespace-pre-wrap text-sm font-sans text-slate-700">{selected?.newValue ?? "Không có"}</pre></div></div></Dialog></>; }
