"use client";
import { ClipboardPlus } from "lucide-react";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { taskService } from "@/services";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { TaskCard } from "@/components/task/task-card";
import { LoadingSkeleton, ErrorState, EmptyState } from "@/components/ui/states";

export default function AdminTasksPage(){
 const client=useQueryClient(); const [open,setOpen]=useState(false); const [planId,setPlanId]=useState(""); const [userId,setUserId]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [dueAt,setDueAt]=useState(""); const [error,setError]=useState<string>();
 const query=useQuery({queryKey:["tasks","all"],queryFn:()=>taskService.listAll()}); const summary=useQuery({queryKey:["tasks","summary"],queryFn:()=>taskService.summary()}); const options=useQuery({queryKey:["tasks","options"],queryFn:()=>taskService.options()});
 if(query.isLoading||summary.isLoading||options.isLoading)return <LoadingSkeleton/>; if(query.isError||summary.isError||options.isError||!options.data)return <ErrorState retry={()=>{query.refetch();summary.refetch();options.refetch();}}/>;
 async function submit(event:React.FormEvent){event.preventDefault();setError(undefined);try{await taskService.create({weeklyPlanId:planId,assigneeUserId:userId,title,description:description||undefined,dueAt:new Date(dueAt).toISOString()});setOpen(false);setTitle("");setDescription("");setDueAt("");await client.invalidateQueries({queryKey:["tasks"]});}catch(caught){setError(caught instanceof Error?caught.message:"Không thể giao nhiệm vụ.");}}
 const counts=summary.data!; const data=query.data??[];
 return <><PageHeader eyebrow="Phân công cá nhân" title="Nhiệm vụ" description="Giao nhiệm vụ và theo dõi trạng thái do máy chủ tính." actions={<Button onClick={()=>setOpen(true)}><ClipboardPlus size={17}/>Giao nhiệm vụ</Button>}/><div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries({"Tổng nhiệm vụ":counts.total,"Đã hoàn thành":counts.completed,"Chưa hoàn thành":counts.incomplete,"Quá hạn":counts.overdue}).map(([label,value])=><div className="card p-4" key={label}><strong className="text-2xl">{value}</strong><p className="text-xs text-slate-500">{label}</p></div>)}</div>{data.length?<div className="grid gap-4 lg:grid-cols-2">{data.map(task=><TaskCard key={task.id} task={task}/>)}</div>:<EmptyState title="Chưa có nhiệm vụ" description="Hãy giao nhiệm vụ đầu tiên."/>}<Dialog open={open} onOpenChange={setOpen} title="Giao nhiệm vụ" description="Người nhận sẽ được đưa vào outbox thông báo sau khi lưu."><form className="grid gap-4" onSubmit={submit}><label><span className="field-label">Kế hoạch tuần *</span><select required className="field" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Chọn kế hoạch</option>{options.data.plans.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span className="field-label">Người nhận *</span><select required className="field" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Chọn người nhận</option>{options.data.users.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span className="field-label">Tiêu đề *</span><input required maxLength={255} className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span className="field-label">Mô tả</span><textarea className="field min-h-20" value={description} onChange={e=>setDescription(e.target.value)}/></label><label><span className="field-label">Hạn hoàn thành *</span><input required type="datetime-local" className="field" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Hủy</Button><Button type="submit">Giao nhiệm vụ</Button></div></form></Dialog></>;
}
